# docker run -d -it -v /path/on/host:/data -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crazycraft-server
  namespace: minecraft
  labels:
    app: crazycraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crazycraft-server
  template:
    metadata:
      labels:
        app: crazycraft-server
    spec:
      volumes:
      - name: crazycraft-data
        persistentVolumeClaim:
          claimName: crazycraft-data-pvc
      containers:
      - name: crazycraft-server
        image: itzg/minecraft-server:java8
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1.5Gi
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MODE
            value: survival
          - name: MOTD
            value: Welcome to the server!
          - name: TYPE
            value: FORGE
          - name: PVP
            value: 'FALSE'
        ports:
        - containerPort: 25565
          name: crazycraft
        volumeMounts:
          - name: crazycraft-data
            mountPath:  /data
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 1.1.1.1
